draw_bold_text_with_bright_colors: true

colors:

  primary:
    background: '#282a36'
    foreground: '#eff0eb'

  cursor:
    cursor: '#97979b'

  selection:
    text:       '#282a36'
    background: '#feffff'

  normal:
    black:   '#282a36'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'

  bright:
    black:   '#686868'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#eff0eb'

window:
  dimensions:
    columns: 120
    lines: 50
  padding:
    x: 5
    y: 5
  scrolling: 10000

bell:
  animation: EaseOutExpo
  duration: 2
  color: '#ffffff'

hints:
    enabled:
      - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
        command: xdg-open
        post_processing: true
        mouse:
            enabled: true
            mods: Control
        binding:
            key: U
            mods: Control|Shift

selection:
  save_to_clipboard: true

